# train
deeper_model: False
N: 10
epsilon: 0.01
x_range_from: 0
x_range_to: 1
val_split: 0.2
weight_path: "./final_report/problem1/weight/weight3_2.pth"  # edit this!
epochs: 10
hidden_layer1: 1024
hidden_layer2: 1024
dropout_ratio: 0.3
lr: 0.001
loss_graph_path: "./final_report/problem1/result/loss_plot3_2.png"  # edit this!

# inference
inf_N: 100
inference_result_graph_path: "./final_report/problem1/result/inference_result_plot3_2.png"  # edit this!